eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
  server:
    enableSelfPreservation: false
spring:
  application:
    name: discovery-server
server:
  port: 8761